const speakButton = document.getElementById("speakButton");
const speechBubble = document.getElementById("speechBubble");

// Array de falas
const messages = [
  'Você quer saber a origem do meu nome? :3',
  'Meu nome é Penny, e aqui é um ambiente seguro!',
  'Aqui é um ambiente seguro! :3',
  'Rawr XD',
  'Comer uma besteira que você gosta pode te deixar feliz, mas sempre com moderação!',
  'Eu não sou um Trojan.',  
  'Cyberbullying eh paia slk.',
  'Qual foi menó me clica ae nao nmrl.',
  'Não sofra sozinho. Procure ajuda de quem você confia.',
  'Hihi~ :3',
  'Você me clicou! :3',
'E você sabia? Segundo a OMS, 1 a cada 6 adolescentes sofre de algum problema de saúde mental.',
'Cuidar da sua saúde mental não significa que você é louco, e sim que você gosta e cuida de si mesmo.',
'Começar é a parte mais difícil, independente do que seja.',
'Aceitar e reconhecer seus defeitos é o primeiro passo para melhorar.',
'Negligenciar sua própria saúde mental pode custar caro para sua saúde física no futuro.',
'Lembre-se: BEBA ÁGUA AGORA!!!',
"'O InterHealth nunca vai pedir a sua senha.' Ref?",
'Você quer saber a origem do meu nome? :3',
'Meu nome é Penny, e aqui é um ambiente seguro!',
'Aqui é um ambiente seguro! :3',
'Rawr XD',
'Comer uma besteira que você gosta pode te deixar feliz, mas sempre com moderação!',
'Eu não sou um Trojan.',
'Cyberbullying é paia slk.',
'Qual foi, menó? Me clica aí não, nmrl.',
'Não sofra sozinho. Procure ajuda de quem você confia.',
'Hihi~ :3',
'Você me clicou! :3',
'uwu',
'Eu gosto muito de assistir Hora de Aventura!',
'Eu gosto muito de assistir Steven Universo!',
'Você já viu nosso vídeo de introdução, hihi?',
'Você é incrível!',
'Nunca desista!',
'Você está indo muito bem!',
'Eu sou melhor que a Lu do Magalu.',
'Eu sou melhor que a Bia do Bradesco.',
'Eu não sou uma IA... Hehe :)',
'Me clicou! :3',
'>:(',
'Yippie!',
'Eu amo assistir vídeos engraçados de gato!',
'Pratique o bem para receber o bem :3!',
'Assista The Midnight Gospel AGORA!',
'Tá afim de dar risada à toa? Assista Superbad.',
'Você pediu uma recomendação de série/filme? Não? Então toma, assista Divertidamente 1 e 2.',
'Tá sem nada pra fazer? Uma ótima recomendação de filme é Viagem de Chihiro.',
'Afim de assistir uma animação big chilling com muita ação? Se sim, veja Gato de Botas 2.',
'Se te interessa conhecer a história mais emocionante e sentimental entre "pai" e filha em um mundo pós-apocalíptico, por favor jogue The Last of Us Parte 1 e 2.',
'Se você gosta de faroeste, cowboys, muita ação, emoção, reviravoltas, gráficos impecáveis e personagens marcantes, jogue Red Dead Redemption 2 (melhor jogo da história).',
'Tá afim de chegar em casa, relaxar e desestressar com um joguinho calmo de um felino muito bonito? Jogue Stray.',
'Me deixa eu pensar. Você quer assistir um filme de comédia, né? Haha, eu sabia. Bom, sendo assim, assista Todo Mundo em Pânico, altos haha.',
'Há coisas que só o tempo cura, infelizmente.',
'Por experiência própria, NÃO gaste dinheiro em jogos online :',
'Vou ler a sua mente agora...',
'Você pensou em "só quero ir para casa slk" calma... pera... você não gosta de mim?',
'Queria comer uma lasanha enormemente colossalmente grande, exatamente AGORA!',
'Paga 10 flexões agora, ou o Corinthians vai cair ano que vem :\ (mentira)',
'Ter coragem também é saber pedir ajuda quando precisa.',
'Não importa quantas vezes você caia, sempre há uma chance de se levantar.',
'Você é mais forte do que pensa, mesmo nos dias em que duvida disso.',
'E você sabia? Segundo a OMS, 1 a cada 6 adolescentes sofre de algum problema de saúde mental.',
'Cuidar da sua saúde mental não significa que você é louco, e sim que você gosta e cuida de si mesmo.',
'Começar é a parte mais difícil, independente do que seja.',
'Aceitar e reconhecer seus defeitos é o primeiro passo para melhorar.',
'Negligenciar sua própria saúde mental pode custar caro para sua saúde física no futuro.',
'Lembre-se: BEBA ÁGUA AGORA!!!',
"'O InterHealth nunca vai pedir a sua senha.' Ref?",
'Você quer saber a origem do meu nome? :3',
'Meu nome é Penny, e aqui é um ambiente seguro!',
'Aqui é um ambiente seguro! :3',
'Rawr XD',
'Comer uma besteira que você gosta pode te deixar feliz, mas sempre com moderação!',
'Eu não sou um Trojan.',
'Cyberbullying é paia slk.',
'Qual foi, menó? Me clica aí não, nmrl.',
'Não sofra sozinho. Procure ajuda de quem você confia.',
'Hihi~ :3',
'Você me clicou! :3',
'uwu',
'Eu gosto muito de assistir Hora de Aventura!',
'Eu gosto muito de assistir Steven Universo!',
'Você já viu nosso vídeo de introdução, hihi?',
'Você é incrível!',
'Nunca desista!',
'Você está indo muito bem!',
'Eu sou melhor que a Lu do Magalu.',
'Eu sou melhor que a Bia do Bradesco.',
'Eu não sou uma IA... Hehe :)',
'Me clicou! :3',
'>:(',
'Yippie!',
'Eu amo assistir vídeos engraçados de gato!',
'Pratique o bem para receber o bem :3!',
'Assista The Midnight Gospel AGORA!',
'Tá afim de dar risada à toa? Assista Superbad.',
'Você pediu uma recomendação de série/filme? Não? Então toma, assista Divertidamente 1 e 2.',
'Tá sem nada pra fazer? Uma ótima recomendação de filme é Viagem de Chihiro.',
'Afim de assistir uma animação big chilling com muita ação? Se sim, veja Gato de Botas 2.',
'Se te interessa conhecer a história mais emocionante e sentimental entre "pai" e filha em um mundo pós-apocalíptico, por favor jogue The Last of Us Parte 1 e 2.',
'Se você gosta de faroeste, cowboys, muita ação, emoção, reviravoltas, gráficos impecáveis e personagens marcantes, jogue Red Dead Redemption 2 (melhor jogo da história).',
'Tá afim de chegar em casa, relaxar e desestressar com um joguinho calmo de um felino muito bonito? Jogue Stray.',
'Me deixa eu pensar. Você quer assistir um filme de comédia, né? Haha, eu sabia. Bom, sendo assim, assista Todo Mundo em Pânico, altos haha.',
'Há coisas que só o tempo cura, infelizmente.',
'Por experiência própria, NÃO gaste dinheiro em jogos online :',
'Vou ler a sua mente agora...',
'Você pensou em "só quero ir para casa slk" calma... pera... você não gosta de mim?',
'Queria comer uma lasanha enormemente colossalmente grande, exatamente AGORA!',
'Paga 10 flexões agora, ou o Corinthians vai cair ano que vem :\ (mentira)',
'Ter coragem também é saber pedir ajuda quando precisa.',
'Não importa quantas vezes você caia, sempre há uma chance de se levantar.',
'Você é mais forte do que pensa, mesmo nos dias em que duvida disso.',
'Que tal dar uma caminhada hj? Vai lá dar uma volta. Veja os benefícios, temos mais informações aqui mesmo no nosso site :3.',
'Tem estado muito ansioso? Eu entendo. Te recomendo ir para a terapia, mas antes você pode se informar aqui!',
'Você sabe tudo sobre si mesmo? Não? Que tal ver um vídeo do Ludo viajante falando sobre isso então?',
'Ei! Não se sinta mal, você é incrível! Leia sobre autoestima bem aqui no nosso site!!',
'Se fosse para apostar eu diria que você NÃO dormiu 8 horas hoje, então eu recomendo que procure mais sobre higiene do sono aqui dentro do site.',
'Ninguém gosta de sofrer bullying, ainda mais na Internet, então se você quer aprender a lidar com o cancelamento do Twitter (X), dá uma olhadinha nos nossos conteúdos.',
'Você já tá a quanto tempo nesse celular ein?? >:c venha ler sobre dependência emocional na nossa página!',
'Eu sei que nessa fase é só poc poc vuc vuc, mas sabia que faz mal consumir conteúdo adulto do tipo? Leia um pouco sobre vício em pornografia na nossa página.',
'Tá estressado? Jogue Kirby Dream Land, um jogo muito fofinho e divertido hihi.',
'Ei! Quer ver uma história épica da dominação dos 4 elementos? Assista Avatar a Lenda de Aang.',
'Eu amo o filme Olhos de Gato, é muito fofo.',
'A história dos jogos Persona 4 e 5 são muito boas!',
'Todos os sentimentos são válidos, se permita sentir!',
];

speakButton.addEventListener("click", () => {
  // Exibe o balão de fala
  speechBubble.style.display = "block";

  // Escolhe uma mensagem aleatória
  const randomIndex = Math.floor(Math.random() * messages.length);
  speechBubble.textContent = messages[randomIndex];

  // Opcional: esconder o balão após 2 segundos
  setTimeout(() => {
    speechBubble.style.display = "none";
  }, 250000);
});

